apiVersion: v2
name: pagopa-ecommerce-event-dispatcher
description: Microservice to schedule events in ecommerce pagoPA
type: application
version: 0.10.4
appVersion: 0.10.4
dependencies:
  - name: microservice-chart
    version: 2.3.1
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
