apiVersion: v2
name: pagopa-ecommerce-event-dispatcher
description: Microservice to schedule events in ecommerce pagoPA
type: application
version: 1.26.0
appVersion: 1.25.0
dependencies:
  - name: microservice-chart
    version: 2.8.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
