apiVersion: v2
name: pagopa-ecommerce-event-dispatcher
description: Microservice to schedule events in ecommerce pagoPA
type: application
version: 1.14.0
appVersion: 1.13.0
dependencies:
  - name: microservice-chart
    version: 2.3.1
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
