apiVersion: v2
name: pagopa-ecommerce-scheduler-service
description: Microservice to schedule events in ecommerce pagoPA
type: application
version: 0.0.3
appVersion: 0.0.3
dependencies:
  - name: microservice-chart
    version: 1.21.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
